FP.TimeTracker.Mvc/Controllers/EmployeeTimeTrackerController.cs
using FP.TimeTracker.Dto.Request;
using FP.TimeTracker.Dto.Respnse;
using FP.TimeTracker.Dto.Response;
using FP.TimeTracker.Mvc.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text;
using System.Threading.Tasks;

namespace FP.TimeTracker.Mvc.Controllers
{
    [Authorize]
    public class EmployeeTimeTrackerController : Controller
    {
        IHttpClientFactory _clientFactory;
        public EmployeeTimeTrackerController(IHttpClientFactory clientFactory)
        {
            _clientFactory = clientFactory;
        }
        public async Task<IActionResult> Index()
        {
            var result = new EmployeesTimeSheetsViewModel() { EmployeeTimesSheets = new List<EmployeeTimeSheetModel> { } };

            var empsResponse = await GetFromHttpClient<List<EmployeeVM>>("TimeTracker/GetEmployeesAsync");
            var empTimeSheetsResponse = await GetFromHttpClient<List<EmployeeTimesheetVM>>("TimeTracker/GetEmployeeTimeSheetsAsync");
            if (empsResponse != null)
            {
                foreach (var employee in empsResponse)
                {
                    var employeeTimeSheets = empTimeSheetsResponse.Where(item => item.EmployeeID == employee.ID).OrderByDescending(item => item.DatePeriod).ToList();
                    var latestEmpPeriod = employeeTimeSheets.FirstOrDefault();
                    if (latestEmpPeriod == null || latestEmpPeriod.DatePeriod.Date != DateTime.Now.Date)
                    {
                        latestEmpPeriod = new EmployeeTimesheetVM
                        {
                            EmployeeID = employee.ID,
                            DatePeriod = DateTime.Now.Date,
                            TimeIn = DateTime.MinValue,
                            TimeOut = DateTime.MinValue
                        };
                    }
                    result.EmployeeTimesSheets.Add(new EmployeeTimeSheetModel
                    {
                        EmployeeID = employee.ID,
                        EmployeeName = employee.EmployeeName,
                        IsActive = employee.IsActive,
                        CurrentTimeSheet = new TimeSheetModel
                        {
                            TimeSheetID = latestEmpPeriod.TimeSheetId,
                            DatePeriod = latestEmpPeriod.DatePeriod,
                            TimeIn = latestEmpPeriod.TimeIn,
                            TimeOut = latestEmpPeriod.TimeOut
                        },
                        TimeSheets = employeeTimeSheets.Select(item => new TimeSheetModel
                        {
                            TimeSheetID = item.TimeSheetId,
                            DatePeriod = item.DatePeriod,
                            TimeIn = item.TimeIn,
                            TimeOut = item.TimeOut
                        }).ToList()
                    });
                }
            }
            return View(result);
        }

        [HttpPost]
        public async Task<IActionResult> SaveTimeSheetJson(EmployeeTimeSheetRequest request)
        {

            var empTimeSheetsResponse = await PostToHttpClient<EmployeeTimeSheetRequest>("TimeTracker/SaveTimeSheetAsync", request);
            return Json(empTimeSheetsResponse);

        }
        [HttpPost]
        public async Task<IActionResult> SaveTimeSheet(EmployeeTimeSheetRequest request)
        {            
            var empTimeSheetsResponse = await PostToHttpClient<EmployeeTimeSheetRequest>("TimeTracker/SaveTimeSheetAsync", request);
            TempData.Add("Message", "Employee time sheet has been added");
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> Activate(int employeeID)
        {
            var data = new EmployeeVM { ID = employeeID };
            var empTimeSheetsResponse = await PostToHttpClient<EmployeeVM>("TimeTracker/ActivateEmployeeAsync", data);
            TempData.Add("Message", "Employee has been acitvated");    
            return RedirectToAction("Index");
        }
        [HttpPost]
        public async Task<IActionResult> DeActivate(int employeeID)
        {
            var data = new EmployeeVM { ID = employeeID };
            var empTimeSheetsResponse = await PostToHttpClient<EmployeeVM>("TimeTracker/DeActivateEmployeeAsync", data);
            TempData.Add("Message", "Employee has been deacitvated");
            return RedirectToAction("Index");
        }

        #region Helper Methods

        private async Task<HttpResponseMessage> PostToHttpClient<T>(string actionMethod, T data)
        {
            var client = getClient();
            if (client != null)
            {
                var response = await client.PostAsJsonAsync<T>(actionMethod, data);
                return response;
            }
            return null;
        }
        private async Task<T> GetFromHttpClient<T>(string actionMethod)
        {
            var client = getClient();
            if (client != null)
            {
                var response = await client.GetFromJsonAsync<T>(actionMethod);
                return response;
            }
            return default(T);
        }
        private HttpClient getClient()
        {
            var claimToken = User.Claims.FirstOrDefault(item => item.Type == "Token");
            if (claimToken != null)
            {
                var token = claimToken.Value.ToString();

                var client = _clientFactory.CreateClient("meta");
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", token);
                return client;
            }
            return null;
        }

        #endregion

    }
}

FP.TimeTracker.Mvc/Controllers/UserController.cs
using FP.TimeTracker.Dto.Response;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Json;
using System.Security.Claims;
using System.Text;
using System.Threading.Tasks;

namespace FP.TimeTracker.Mvc.Controllers
{
    public class UserController : Controller
    {
        IHttpClientFactory _clientFactory;
        public UserController(IHttpClientFactory clientFactory)
        {
            _clientFactory = clientFactory;
        }
        [AllowAnonymous]
        public IActionResult Index()
        {
            return RedirectToAction("Login", "Public");
        }
       
      
        [HttpGet]
        [AllowAnonymous]
        public async Task<IActionResult> Logout()
        {
            if (User.Identity.IsAuthenticated)
            {
                await HttpContext.SignOutAsync();//(CookieAuthenticationDefaults.AuthenticationScheme, principal);
            }
            return RedirectToAction("Login", "Public");
        }
    }
}

FP.TimeTracker.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FP.TimeTracker.Mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link href="~/lib/jquery-ui-1.12.1/jquery-ui.min.css" rel="stylesheet" />
    <link href="~/lib/timepicker-1.3.5/jquery.timepicker.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Time Tracker Demo App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmployeeTimeTracker" asp-action="Index">Time Tracker</a>
                        </li>
                    </ul>
                </div>
                <div>
                    <p class="brand"><div class="welcome">Welcome, @(User.Identity.IsAuthenticated ? User.Identity.Name : "Guest") <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Logout">Logout</a></div></p>
                </div>
            </div>
        </nav>
    </header>
    <div class="container container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - FP.TimeTracker.Mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-ui-1.12.1/jquery-ui.min.js"></script>
    <script src="~/lib/timepicker-1.3.5/jquery.timepicker.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>